# 프로그램 흐름의 제어
## 조건문
+ if, else, else if
```kotlin
fun main(args: Array<String>) {
    val a = 12
    val b = 7
    val max = if (a > b) {
        a
    } else if (a == b) {
        b
    } else {
	0
    }
    println(max) // 12
}
```
if문을 사용하면 조건식의 참과 거짓을 판별해서 프로그램의 흐름을 제어할 수 있다.   
else if는 필요한 만큼 조합할 수 있다.
+ when
```kotlin
fun main(args: Array<String>) {
    val x = 1
    when(x){
        1 -> println("x == 1")
        2, 3 -> println("x == 2 or x == 3")
        else -> {
            println("x는 1, 2, 3이 아닙니다.")
        }
    } // x == 1
}
```
when문은 인자에 일치하는 값 또는 표현식에 따라 프로그램의 흐름을 제어한다.   
표현식은 함수의 반환값, in 연산자를 사용한 범위, is 키워드를 사용한 자료형 판별 등 다양한 조건을 처리할 수 있다.   
인자가 없는 when문도 사용할 수 있다.  
   
## 반복문
+ for문
```kotlin
fun main(args: Array<String>) {
    var sum = 0
    for (x in 1..10) {
        sum += x
    }
    println(sum) // 55
}
```
for문은 in연산자를 사용해 지정한 횟수만큼 본문을 반복해서 실행한다.   
   
+ in연산자
```kotlin
fun main(args: Array<String>) {
    for (i in 1..5) print(i) // 1 에서 5 까지 증가
    for (i in 1 until 5) print(i) // 1 에서 5미만 까지 증가
    for (i in 5 downTo 1) print(i) // 5 에서 1 까지 감소
    for (i in 1..5 step 2) print(i) // 1 에서 5 까지 2씩 증가
}
```
   
+ 피라미드 출력
```kotlin
fun main(args: Array<String>) {
    pyramid(5)
}

fun pyramid(a: Int) {
    for (i in 1 .. a) {
        for (j in 0 until a - i) {
            print(" ")
        }
        for (k in 1 until i * 2) {
            print("*")
        }
        println()
    }
}
```
   
+ while문
```kotlin
fun main(args: Array<String>) {
    var number = 5
    var factorial = 1L
    while (number > 0) { // number가 0 보다 클 경우 본문 실행
        factorial *= number
        number--
    }
    println(factorial) // 120
}
```
while문은 조건식이 true인 경우 분문을 실행하는 반복문이다.   
조건식이 false가 되지 않으면 무한루프에 빠지기 때문에 주의해야 한다.
+ do-while문
```kotlin
fun main(args: Array<String>) {
    do {
        println("본문을 실행 했습니다.")
    } while (false)
} // 본문을 실행 했습니다.
```
do-while문은 조건식이 거짓이더라도 본문을 적어도 한번은 실행한다.
   
## 흐름의 제어문
+ return : 함수에서 결괏값을 변환하거나 지정된 라벨로 이동
+ break : for나 while의 조건식에 상관없이 반복문을 끝냄
+ continue : for 나 while의 반복문의 본문을 모두 수행하지 않고 다시 조건으로 넘어감   
   
+ return
```kotlin
fun main(args: Array<String>) {
    retFunc()
    // start of retFunc
}

inline fun inlinelambda(a: Int, b: Int, out: (Int, Int) -> Unit) {
    out(a, b)
}

fun retFunc() {
    println("start of retFunc")
    inlinelambda(13, 3) { x, y ->
        val result = x + y
        if (result > 10) return
        println(result)
    }
    println("end of retFunc")
} // return이 실행되면 이 곳으로 흐름이 이동
```
위의 예제에서 retFunc()함수안에 있는 람다식에서 return이 실행되었다. 이렇게 람다식에서 return이 실행되면 외부에 있는 함수 밖으로 흐름이 이동한다. 이를 방지하기 위해서 라벨을 사용한다.   
```kotlin
fun main(args: Array<String>) {
    retFunc()
    // start of reFunc
    // end of retFunc
}

inline fun inlinelambda(a: Int, b: Int, out: (Int, Int) -> Unit) {
    out(a, b)
}

fun retFunc() {
    println("start of retFunc")
    inlinelambda(13, 3) lit@{ x, y ->
        val result = x + y
        if (result > 10) return@lit
        println(result)
    } // return이 실행되면 이 곳으로 흐름이 이동
    println("end of retFunc")
}
```
람다식 블록의 시작 부분에 lit라는 라벨(@)을 지정했고 return@lit이 실행되면서 라벨이 지정된 람다식 블록의 끝부분으로 흐름이 이동했다.
```kotlin
...
fun retFunc() {
    println("start of retFunc")
    inlinelambda(13, 3) { x, y ->
        val result = x + y
        if (result > 10) return@inlineLambda
        println(result)
    } // return이 실행되면 이 곳으로 흐름이 이동
    println("end of retFunc")
}
...
```
암묵적(묵시적)라벨 : 식의 시작부분에 라벨은 생략하고 return@함수명으로 라벨을 사용할 수 있다.   
일반적을 return을 사용해야하는 경우에는 람다식 보다 익명함수를 사용하는 것이 직관적이고 가독성이 좋다.

+ break, continue
```kotlin
fun main(args: Array<String>) {
    for (i in 1..5) {
        if (i == 3) break
        print(i)
    } // 12
    println()
    for (i in 1..5) {
        if (i == 3) continue
        print(i)
    } // 1245
}
```
break와 continue를 사용하면 for, while, do-while문 루프를 빠져 나온다.   
break는 이후의 반복이 전부 종료된다.   
continue는 현재 실행되고 있는 본문이 종료되고 다음 반복이 실행된다.   
   
## 예외 처리문
+ 예외(exception) : 실행 도중 잠재적인 오류로 비정상적으로 프로그램이 종료되는 경우
	+ 운영체제의 문제
	+ 입력값의 문제
	+ 받아들일 수 없는 연산 (0으로 나누기 등)
	+ 메모리의 할당 실패 및 부족
	+ 컴퓨터 기계 자체의 문제 (하드웨어 문제)

```kotlin
try {
	예외 발생 가능성 있는 문장
} catch (e : 예외처리 클래스명) {
	예외를 처리하기 위한 문장
} finally {
	반드시 실행됭야 하는 문장 // 없다면 생략가능
}
```
+ try{} catch{} finally{} : 블록의 본문(try)을 수행하는 도중 예외가 발생하면 catch 블록의 본문을 실행 fianlly 블록의 본문은 예외가 발생해도 항상 실행된다.   
   
```kotlin
fun main(args: Array<String>) {
    val a = 6
    val b = 0
    val c: Int
    try {
        c = a / b
    } catch (e : Exception){
        println("Exception is handled")
    } finally {
        println("반드시 실행 된다")
    }
}
```
```
Exception is handled
반드시 실행된다.
```
위의 예제에서 6을 0으로 나눠서 예외가 발생했고 catch블록의 본문이 실행되었다. 예외발생과 별개로 finally블록의 본문은 실행되었다.   
   
+ 예외 발생시키기
```kotlin
throw Exception(message: String)
```
throw키워드로 특정 조건에 따른 예외를 처리할 수 있다.
```kotlin
fun main(args: Array<String>) {
    var amount = 600
    try {
        amount -= 100
        checkAmount(amount)
    } catch (e: Exception) {
        println(e.message)
    } finally {
        println("amount : $amount")
    }
}

fun checkAmount(amount: Int) {
    if (amount < 1000) {
        throw Exception("잔고가 $amount 으로 1000 미만입니다.")
    }
}
```
```
잔고가 500 으로 1000 미만입니다.
amount : 500
```
+ 사용자 예외 정의
```
Class <사용자 예외 클래스명>(message: String) : Exception(message)
```
```kotlin
class InvalidNameException(message: String) : Exception(message)

fun main(args: Array<String>) {
    var name = "kildong123"
    try {
        validateName(name)
    } catch (e: InvalidNameException) { // 숫자가 포함된 예외 처리
        println(e.message)
    } catch (e: Exception) { // 기타 예외 처리
        println(e.message)
    }
}

fun validateName(name: String) { // 이름에 숫자가 포함됭 있으면 예외 던지기
    if (name.matches(Regex(".*\\d+."))) {
        throw InvalidNameException("Your name : $name : contains numerals")
    }
}
```